Task_1_1_3
Vovadinamik8913/OOP pull request #6
Opened 2024-09-13 06:49 UTC by Vovadinamik8913

2024-10-07 08:12 UTC, shadrina requested changes

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/Main.java
> +    public static void main(String[] args) {
В целом, вы не обязаны делать main, если приложение не консольное. Тестов достаточно.

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/Parser.java
> +        Pattern special = Pattern.compile("[!@#$%&_=|<>?{}\\[\\]~\"';:]");
Использовать в этой задаче регулярки - конечно, читерство. Но раз я поздно сказала, переделка опциональна. Хотелось, чтобы вы парсили руками.

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/Parser.java
> +        Pattern special = Pattern.compile("[!@#$%&_=|<>?{}\\[\\]~\"';:]");
Расскажешь, как внутри работает Matcher

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/Parser.java
> +        }
Switch expression please. С бросанием исключения в исключительной ситуации

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/Parser.java
> +            char operation, Expression a, Expression b) throws Exception {
Оно же ничего не кидает, зачем?

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/Main.java
> +            Expression e = Parser.parse(expression, new int[]{0});
Очень странно выглядит этот второй аргумент. Кажется, это детали реализации? Сделай перегрузку, которая принимает только выражение и сама подкладывает этот волшебный второй аргумент.

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Add.java
> +        if (left.getClass() == Number.class && right.getClass() == Number.class) {
Оператор `instanceof`

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Div.java
> +        if (left.getClass() == Number.class && right.getClass() == Number.class) {
Аналогично

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Expression.java
> +    }
Я думаю, по семантике это обычный `toString()`

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Expression.java
> +    public abstract Expression simplify() throws Exception;
Прямо в интерфейсе прописывать насколько общее исключение не стоит. А в этом случае уж точно.
У тебя получается так, что исключения-то почти никто не кидает, а клиенты вынуждены все зазря оборачивать в try-catch. Пользуйся лучше runtime исключениями и прописывай их в throws соответствующих методов наследников. А интерфейс оставь чистый.

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Mul.java
> +        if (left.getClass() == Number.class && right.getClass() == Number.class) {
Аналогично, оператор instanceof

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Mul.java
> +            return new Number(left.eval(null) * right.eval(null));
Как-то все это странно выглядит с null'ами... Чего хотелось этим добиться?

2024-10-07 08:12 UTC, shadrina commented on Task_1_1_3/src/test/java/ru/nsu/abramenko/ParserTest.java
> +        Main.main(null);
Убирай main, тестируй сразу функциональность напрямую.

2024-10-07 14:03 UTC, Vovadinamik8913 commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/Parser.java
> +        Pattern special = Pattern.compile("[!@#$%&_=|<>?{}\\[\\]~\"';:]");
> Использовать в этой задаче регулярки - конечно, читерство. Но раз я поздно сказала, переделка опциональна. Хотелось, чтобы вы парсили руками.
Изначально просто парсилось, но для ошибок и поиска я подумал, что будет выглядеть лучше через регулярки

2024-10-07 14:04 UTC, Vovadinamik8913 commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/Parser.java
> +            char operation, Expression a, Expression b) throws Exception {
> Оно же ничего не кидает, зачем?

Я в конструкторе DIV делаю проверку на деление на 0, поэтому здесь появляется exception

2024-10-07 14:05 UTC, Vovadinamik8913 commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Mul.java
> +            return new Number(left.eval(null) * right.eval(null));
> Как-то все это странно выглядит с null'ами... Чего хотелось этим добиться?

ну eval от числа это его значение, зачем передавать там строку

2024-10-08 02:42 UTC, Vovadinamik8913 commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Expression.java
> +    public abstract Expression simplify() throws Exception;
> Прямо в интерфейсе прописывать насколько общее исключение не стоит. А в этом случае уж точно. У тебя получается так, что исключения-то почти никто не кидает, а клиенты вынуждены все зазря оборачивать в try-catch. Пользуйся лучше runtime исключениями и прописывай их в throws соответствующих методов наследников. А интерфейс оставь чистый.

я изначально хотел сделать в отдельных, но  exception возникает в eval variable при неправильном вводе из-за чего приходится его учитываь в других eval и тогда получается, что проще сделать в интерфейс exception

2024-10-08 09:00 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/Parser.java
> +                || text.charAt(pos[0]) == '\t' || text.charAt(pos[0]) == '\r') {
Вынести в переменную

2024-10-08 09:00 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Variable.java
> +            throw  new NullPointerException("Конфликт имен: variable = null");
`@NotNull`

2024-10-08 09:00 UTC, shadrina commented on Task_1_1_3/src/test/java/ru/nsu/abramenko/ParserTest.java
> +        assertTrue(true);
assertThrows

2024-10-14 12:00 UTC, shadrina requested changes

2024-10-14 12:00 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Expression.java
> +    protected Expression right;
Так, я каким-то образом проморгала это на паре. Почему у абстрактного выражения есть правая и левая часть? Оно уже тогда никакое не абстрактное.

2024-10-14 12:00 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Expression.java
> +    }
Нет, не надо сравнивать строки. Надо нормально сравнивать соответствующие части-объекты у соответствующих классов. Эти методы переопределяются для каждого конкретного класса.

2024-10-15 07:24 UTC, shadrina requested changes

2024-10-15 07:24 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Add.java
> +        if (right instanceof Number && right.eval("") == 0) {
Я уже писала, но не надо использовать eval в simplify?

2024-10-15 07:24 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/abramenko/math/Add.java
> +        if (right instanceof Number && right.eval("") == 0) {
Бери значение у Number, ты же знаешь, что это Number и там внутри обязательно лежит значение

2024-10-22 13:03 UTC, merged